import { Wallet } from "@/types";

export const wallets: Wallet[] = [
    {
        id: "metamask",
        name: "MetaMask",
        icon: "/images/MetaMask.avif",
        popular: true,
    },
    {
        id: "coinbasewallet",
        name: "Coinbase Wallet",
        icon: "/images/Coinbase Wallet.avif",
        popular: true,
    },
    {
        id: "coinwallet",
        name: "Coin Wallet",
        icon: "/images/Coin Wallet.webp",
        popular: true,
    },
    {
        id: "trustwallet",
        name: "Trust Wallet",
        icon: "/images/TrustWallet.webp",
        popular: true,
    },
    {
        id: "phantom",
        name: "Phantom",
        icon: "/images/Phantom Wallet.avif",
        popular: true,
    },
    {
        id: "zengo",
        name: "Zengo",
        icon: "/images/ZenGo.webp",
        popular: true,
    },
    {
        id: "rainbow",
        name: "Rainbow",
        icon: "/images/Rainbow.avif",
        popular: true,
    },
    {
        id: "argent",
        name: "Argent",
        icon: "/images/Argent.avif", // PNG from official site
        popular: true,
    },
    {
        id: "ledger",
        name: "Ledger",
        icon: "/images/Ledger.svg",
        popular: true,
    },
    {
        id: "trezor",
        name: "Trezor",
        icon: "/images/Trezor.avif",
        popular: true,
    },
    {
        id: "rabby",
        name: "Rabby Wallet",
        icon: "/images/Rabby Wallet.avif",
        popular: true,
    },
    {
        id: "okx",
        name: "OKX Wallet",
        icon: "/images/OKX Wallet.webp", // Official logo
        popular: true,
    },
    {
        id: "safepal",
        name: "SafePal",
        icon: "/images/SafePal.svg",
        popular: true,
    },
    {
        id: "alchemy",
        name: "Alchemy",
        icon: "/images/Alchemy.svg", // PNG from official site
        popular: true,
    },

    {
        id: "coinbasesmartwallet",
        name: "Coinbase Smart Wallet",
        icon: "/images/Coinbase Smart Wallet.avif",
        popular: true,
    },
    {
        id: "ellipal",
        name: "Ellipal",
        icon: "/images/Ellipal.avif",
        popular: true,
    },
    {
        id: "blockwallet",
        name: "BlockWallet",
        icon: "/images/BlockWallet.avif",
        popular: true,
    },
    {
        id: "kraken",
        name: "Kraken",
        icon: "/images/Kraken Wallet.avif",
        popular: true,
    },
    {
        id: "myetherwallet",
        name: "MyEtherWallet",
        icon: "/images/MyEtherWallet.avif",
        popular: true,
    },
    {
        id: "dcent",
        name: "DCent",
        icon: "/images/DCENT.avif",
        popular: true,
    },
    {
        id: "sepior",
        name: "Sepior",
        icon: "/images/Sepior.avif",
        popular: true,
    },
    {
        id: "qredo",
        name: "Qredo",
        icon: "/images/Qredo.avif",
        popular: true,
    },

    {
        id: "goki",
        name: "Goki",
        icon: "/images/Goki.avif",
        popular: true,
    },

    {
        id: "openfort",
        name: "OpenFort",
        icon: "/images/OpenFort.webp",
        popular: true,
    },

    {
        id: "safe",
        name: "Safe",
        icon: "/images/Safe.avif",
        popular: true,
    },

    {
        id: "snowflake",
        name: "Snowflake",
        icon: "/images/Snowflake.avif",
        popular: true,
    },
    {
        id: "castle",
        name: "Castle",
        icon: "/images/Castle.webp",
        popular: true,
    },
    {
        id: "dfns",
        name: "Dfns",
        icon: "/images/Dfns.avif",
        popular: true,
    },
    {
        id: "candide",
        name: "Candide",
        icon: "/images/Candide.webp",
        popular: true,
    },
    {
        id: "zerion",
        name: "Zerion",
        icon: "/images/Zerion.avif",
        popular: true,
    },
    {
        id: "taho",
        name: "Taho",
        icon: "/images/Taho Wallet.svg",
        popular: true,
    },
    {
        id: "solflare",
        name: "Solflare",
        icon: "/images/Solflare.webp",
        popular: true,
    },
    {
        id: "uni",
        name: "UniPass",
        icon: "/images/UniPass.svg",
        popular: true,
    },
    {
        id: "soul",
        name: "Soul Wallet",
        icon: "/images/Soul Wallet.webp",
        popular: true,
    },
    {
        id: "cashmere",
        name: "Cashmere",
        icon: "/images/Cashmere.avif",
        popular: true,
    },
    {
        id: "mew",
        name: "MEW wallet",
        icon: "/images/MEW wallet.avif",
        popular: true,
    },
    {
        id: "stackup",
        name: "Stackup",
        icon: "/images/Stackup.webp",
        popular: false,
    },
    {
        id: "sequence",
        name: "Sequence",
        icon: "/images/Sequence.avif",
        popular: false,
    },
    {
        id: "enkrypt",
        name: "Enkrypt",
        icon: "/images/Enkrypt.svg",
        popular: false,
    },
    {
        id: "obvious",
        name: "Obvious",
        icon: "/images/Obvious.avif",
        popular: false,
    },
    {
        id: "alphawallet",
        name: "AlphaWallet",
        icon: "/images/AlphaWallet.avif",
        popular: false,
    },
    {
        id: "imtoken",
        name: "imToken",
        icon: "/images/imToken.avif",
        popular: false,
    },
    {
        id: "tokenpocket",
        name: "TokenPocket",
        icon: "/images/TokenPocket.avif",
        popular: false,
    },
    {
        id: "multis",
        name: "Multis",
        icon: "/images/Multis.avif",
        popular: false,
    },
    {
        id: "coin98",
        name: "Coin98",
        icon: "/images/Coin98.avif",
        popular: false,
    },
    {
        id: "alfa1",
        name: "Alfa1",
        icon: "/images/Alfa1.avif",
        popular: false,
    },
    {
        id: "venly",
        name: "Venly",
        icon: "/images/Venly.avif",
        popular: false,
    },
    {
        id: "frontier",
        name: "Frontier Wallet",
        icon: "/images/Frontier Wallet.avif",
        popular: false,
    },
    {
        id: "dapppocket",
        name: "Dapp Pocket",
        icon: "/images/Dapp Pocket.avif",
        popular: false,
    },
    {
        id: "ronin",
        name: "Ronin Wallet",
        icon: "/images/Ronin Wallet.avif",
        popular: false,
    },
    {
        id: "arculus",
        name: "Arculus",
        icon: "/images/Arculus.avif",
        popular: false,
    },
    {
        id: "pier",
        name: "Pier Wallet",
        icon: "/images/Pier Wallet.avif",
        popular: false,
    },
    {
        id: "xdefi",
        name: "XDEFI Wallet",
        icon: "/images/XDEFI Wallet.avif",
        popular: false,
    },
    {
        id: "clear",
        name: "Clear EVM Wallet",
        icon: "/images/Clear EVM Wallet.avif",
        popular: false,
    },

    {
        id: "narval",
        name: "Narval",
        icon: "/images/Narval.avif",
        popular: false,
    },
    {
        id: "wallet3",
        name: "Wallet 3",
        icon: "/images/Wallet 3.webp",
        popular: false,
    },
    {
        id: "etherspot",
        name: "Etherspot SDK",
        icon: "/images/Etherspot SDK.webp",
        popular: false,
    },
    {
        id: "pillar",
        name: "Pillar",
        icon: "/images/Pillar.avif",
        popular: false,
    },
    {
        id: "ambire",
        name: "Ambire Wallet",
        icon: "/images/Ambire Wallet.avif",
        popular: false,
    },
    {
        id: "bitcoincom",
        name: "Bitcoin.com Wallet",
        icon: "/images/Bitcoin.com Wallet.avif",
        popular: false,
    },
    {
        id: "bls",
        name: "BLS Wallet",
        icon: "/images/BLS Wallet.avif",
        popular: false,
    },
    {
        id: "plena",
        name: "Plena Finance",
        icon: "/images/Plena Finance.avif",
        popular: false,
    },
    {
        id: "fluvi",
        name: "Fluvi Wallet",
        icon: "/images/Fluvi Wallet.avif",
        popular: false,
    },
    {
        id: "squads",
        name: "Squads",
        icon: "/images/Squads.avif",
        popular: false,
    },
    {
        id: "mpc",
        name: "MPC Vault",
        icon: "/images/MPCVault.webp",
        popular: false,
    },
    {
        id: "infinity",
        name: "Infinity Wallet",
        icon: "/images/Infinity Wallet.avif",
        popular: false,
    },
    {
        id: "unstoppable",
        name: "Unstoppable Wallet",
        icon: "/images/Unstoppable Wallet.avif",
        popular: false,
    },
    {
        id: "ha",
        name: "HaHa Wallet",
        icon: "/images/HaHa Wallet.avif",
        popular: false,
    },
    {
        id: "ancrypto",
        name: "AnCrypto",
        icon: "/images/AnCrypto.avif",
        popular: false,
    },
    {
        id: "kryptogo",
        name: "KryptoGO Wallet",
        icon: "/images/KryptoGO Wallet.avif",
        popular: false,
    },
    {
        id: "sender",
        name: "Sender",
        icon: "/images/Sender.webp",
        popular: false,
    },
    {
        id: "kuma",
        name: "Kuma Wallet",
        icon: "/images/Kuma Wallet.webp",
        popular: false,
    },
    {
        id: "ultimate",
        name: "Ultimate",
        icon: "/images/Ultimate.avif",
        popular: false,
    },
    {
        id: "martian",
        name: "Martian Wallet",
        icon: "/images/Martian Wallet.webp",
        popular: false,
    },
    {
        id: "gem",
        name: "Gem Wallet",
        icon: "/images/Gem Wallet.avif",
        popular: false,
    },
    {
        id: "zkbob",
        name: "zkBob",
        icon: "/images/zkBob.avif",
        popular: false,
    },
    {
        id: "holdstation",
        name: "Holdstation",
        icon: "/images/Holdstation.avif",
        popular: false,
    },
    {
        id: "sinohope",
        name: "SinoHope",
        icon: "/images/SinoHope.avif",
        popular: false,
    },
    {
        id: "linen",
        name: "Linen",
        icon: "/images/Linen.avif",
        popular: false,
    },
    {
        id: "cobo",
        name: "Cobo",
        icon: "/images/Cobo.webp",
        popular: false,
    },
    {
        id: "locksmith",
        name: "Locksmith Wallet",
        icon: "/images/Locksmith Wallet.avif",
        popular: false,
    },
    {
        id: "bizzllet",
        name: "Bizzllet",
        icon: "/images/Bizzllet.avif",
        popular: false,
    },
    {
        id: "myrkle",
        name: "Myrkle",
        icon: "/images/Myrkle.avif",
        popular: false,
    },
    {
        id: "guarda",
        name: "Guarda Wallet",
        icon: "/images/Guarda Wallet.webp",
        popular: false,
    },
    {
        id: "gridlock",
        name: "Gridlock",
        icon: "/images/Gridlock.avif",
        popular: false,
    },
    {
        id: "rivo",
        name: "Rivo",
        icon: "/images/Rivo.xyz.avif",
        popular: false,
    },
    {
        id: "bitget",
        name: "Bitget Wallet",
        icon: "/images/Bitget Wallet.avif",
        popular: false,
    },
    {
        id: "biconomy",
        name: "Biconomy",
        icon: "/images/Biconomy.avif",
        popular: false,
    },
    {
        id: "aarc",
        name: "Aarc",
        icon: "/images/Aarc.avif",
        popular: false,
    },
    {
        id: "web3asy",
        name: "Web3asy",
        icon: "/images/Web3asy.avif",
        popular: false,
    },
    {
        id: "wigwam",
        name: "Wigwam",
        icon: "/images/Wigwam.webp",
        popular: false,
    },
    {
        id: "atomic",
        name: "Atomic Wallet",
        icon: "/images/Atomic Wallet.avif",
        popular: false,
    },
    {
        id: "datacurve",
        name: "DataCurve",
        icon: "/images/DataCurve.avif",
        popular: false,
    },
    {
        id: "sorted",
        name: "Sorted Wallet",
        icon: "/images/Sorted Wallet.avif",
        popular: false,
    },
    {
        id: "walletkit",
        name: "WalletKit",
        icon: "/images/WalletKit.avif",
        popular: false,
    },
    {
        id: "virgo",
        name: "Virgo Wallet",
        icon: "/images/Virgo Wallet.avif",
        popular: false,
    },
    {
        id: "bitpowr",
        name: "Bitpowr",
        icon: "/images/Bitpowr.webp",
        popular: false,
    },
    {
        id: "ownbit",
        name: "Ownbit",
        icon: "/images/Ownbit.webp",
        popular: false,
    },
    {
        id: "fordefi",
        name: "Fordefi",
        icon: "/images/Fordefi.avif",
        popular: false,
    },
    {
        id: "fintopio",
        name: "Fintopio",
        icon: "/images/Fintopio.avif",
        popular: false,
    },
    {
        id: "saakuru",
        name: "Saakuru",
        icon: "/images/Saakuru.avif",
        popular: false,
    },

    {
        id: "eco",
        name: "ECOIN Wallet",
        icon: "/images/ECOIN Wallet.avif",
        popular: false,
    },
    {
        id: "timeless",
        name: "Timeless X",
        icon: "/images/Timeless X.avif",
        popular: false,
    },
    {
        id: "degen",
        name: "Degen Wallet",
        icon: "/images/Degen Wallet.webp",
        popular: false,
    },
    {
        id: "mass",
        name: "Mass",
        icon: "/images/Mass.webp",
        popular: false,
    },
    {
        id: "mini",
        name: "MiniPay",
        icon: "/images/MiniPay.webp",
        popular: false,
    },
    {
        id: "xverse",
        name: "Xverse Wallet",
        icon: "/images/Xverse Wallet.avif",
        popular: false,
    },
    {
        id: "utila",
        name: "Utila",
        icon: "/images/Utila.avif",
        popular: false,
    },
    {
        id: "labyrinth",
        name: "Labyrinth",
        icon: "/images/Labyrinth.avif",
        popular: false,
    },
    {
        id: "cregis",
        name: "Cregis",
        icon: "/images/Cregis.avif",
        popular: false,
    },
    {
        id: "zypto",
        name: "Zypto Wallet",
        icon: "/images/Zypto Wallet.avif",
        popular: false,
    },
    {
        id: "umpc",
        name: "uMPC",
        icon: "/images/uMPC.webp",
        popular: false,
    },
    {
        id: "total",
        name: "TotalSig",
        icon: "/images/TotalSig.avif",
        popular: false,
    },
    {
        id: "io",
        name: "io.finnet",
        icon: "/images/io.finnet.avif",
        popular: false,
    },
    {
        id: "nufi",
        name: "NuFi",
        icon: "/images/NuFi.avif",
        popular: false,
    },

    {
        id: "pass",
        name: "Pass App",
        icon: "/images/Pass App.avif",
        popular: false,
    },
    {
        id: "clave",
        name: "Clave",
        icon: "/images/Clave.avif",
        popular: false,
    },
];
